// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
sidebar: [
    'intro',
    {
      type: 'category',
      label: 'Classic',
      items: [
        {type: 'autogenerated',
        dirName: 'classic-templates'},
      ],
      link:
      {
        type:'doc',
        id: 'classic-templates/serverDeploy,'
      }
    },
  ],

};

module.exports = sidebars;``