<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:com.corticon.rulesemf.canonicalvocabularymodel="http:///com/corticon/rulesemf/canonicalvocabularymodel.ecore" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="root" nsURI="http://root/1.0" nsPrefix="root">
  <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
    <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:RootExtension" majorVersionNumber="6" minorVersionNumber="3" minorServiceNumber="3" buildNumber="8020" updateStamp="_deYNckioEe2Zg-UFYAaT4Q" externalChecksum="2722078124:507989954" studioType="Java" customDataTypeDisplayCount="50">
      <languageCode>en_US</languageCode>
      <databaseAccess databasePropertyDisplayCount="50"/>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//destinationType">
        <dataTypeName manuallyCreated="true" value="destinationType"/>
        <baseDataType manuallyCreated="true" value="String"/>
        <enumeration manuallyCreated="true" value="true"/>
        <enumerationElements>
          <value manuallyCreated="true" value="'US'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Puerto Rico'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'Canada'"/>
        </enumerationElements>
        <enumerationElements>
          <value manuallyCreated="true" value="'London'"/>
        </enumerationElements>
      </customDataTypeList>
      <customDataTypeList enumerationDisplayCount="50" eDataType="#//cubicSizeType">
        <dataTypeName manuallyCreated="true" value="cubicSizeType"/>
        <baseDataType manuallyCreated="true" value="Decimal"/>
        <enumeration manuallyCreated="true" value="false"/>
        <constraintExpression manuallyCreated="true" external="value &lt;5184 or value >=5184"/>
      </customDataTypeList>
    </contents>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Package"/>
        <datastorePersistent manuallyCreated="true" value="true"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="length"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="depth"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="height"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actualWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="actualWeight"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimensionalWeight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="dimensionalWeight"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination" eType="#//destinationType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.0">
          <name manuallyCreated="true" value="destination"/>
          <mode manuallyCreated="true" value="Base"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="volume" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigDecimal">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension">
          <name manuallyCreated="true" value="volume"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cubicSize" eType="#//cubicSizeType">
      <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
        <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:AttributeExtension" customDataType="#//%http:%2F%2F%2Fcom%2Fcorticon%2Frulesemf%2Fcanonicalvocabularymodel%2FVocabularyExtension%/@contents.0/@customDataTypeList.1">
          <name manuallyCreated="true" value="cubicSize"/>
          <mode manuallyCreated="true" value="ExtendedTransient"/>
        </contents>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Notes">
    <eAnnotations source="http:///com/corticon/rulesemf/canonicalvocabularymodel/VocabularyExtension">
      <contents xsi:type="com.corticon.rulesemf.canonicalvocabularymodel:EntityExtension">
        <name manuallyCreated="true" value="Notes"/>
        <datastorePersistent manuallyCreated="true" value="true"/>
        <datastoreCaching manuallyCreated="true" value="false"/>
      </contents>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="destinationType">
    <eLiterals name="V0" literal="'US'"/>
    <eLiterals name="V1" value="1" literal="'Puerto Rico'"/>
    <eLiterals name="V2" value="2" literal="'Canada'"/>
    <eLiterals name="V3" value="3" literal="'London'"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="cubicSizeType" instanceClassName="java.math.BigDecimal"/>
</ecore:EPackage>
